### ISSUE TITLE
No knexfile found in this directory. Specify a path with --knexfile

### ISSUE THREAD

**Issue by Telegramsrv** [Piterden/syntax-highlighter-bot#1]
![knex_1](https://user-images.githubusercontent.com/22915282/35338089-fde120d8-012d-11e8-9536-f605598b589a.PNG)

**Comment by Piterden** [comment]
Fixed 
https://github.com/Piterden/syntax-highlighter-bot/commit/45061c2c2ee33604e61ac9b13419ea11ea70f349

**Comment by Telegramsrv** [comment]
Не пофикшено, даже шторм теперь не подсвечивает ссылку на файл. Ошибка та же `No knexfile found in this directory. Specify a path with --knexfile`
![knex_2](https://user-images.githubusercontent.com/22915282/35374374-ad1cea0c-01b3-11e8-8403-b1933e8a0713.PNG)

**Comment by Piterden** [comment]
https://github.com/Piterden/syntax-highlighter-bot/blob/1.0/knexfile.js

**Comment by Piterden** [comment]
You can specify the file and make a PR
